CREATE EXTENSION IF NOT EXISTS "pg_trgm";
ALTER TABLE resources ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT FALSE;
ALTER TABLE services ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT FALSE;
