name: Stage 4 - Security Tests

on:
  push:
    branches: [ main, develop, stage-qa-e2e ]
  pull_request:
    branches: [ main ]
    
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Run npm audit
        run: npm audit --audit-level=high
        
      - name: Run ESLint security plugin
        run: |
          npm install eslint @typescript-eslint/eslint-plugin @typescript-eslint/parser eslint-plugin-security
          npx eslint --ext .ts,.tsx --plugin security --rule 'security/detect-non-literal-fs-filename: error' .
          
      - name: Check for secret leaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: 'http://localhost:3000'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'